INSERT INTO publisher (`address`, `name`, `YearsOfPublish`) VALUES ("25, Hai Bà Trưng, Hà Nội", "Kim Đồng", 2013);
INSERT INTO publisher (`address`, `name`, `YearsOfPublish`) VALUES ("32a, Tôn Đức Thắng, Hà Nội", "Nhã Nam", 2017);
INSERT INTO publisher (`address`, `name`, `YearsOfPublish`) VALUES ("Quận 1, Tp Hồ Chí Minh", "Đan Đan", 2004);
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID2`, `National`, `TranslateLanguage`, `seasons`) VALUES ("2", "book1","Tôi thấy hoa rơi", 402, "Sách hay cho giới trẻ", 1992, 1, "Việt Nam", "Việt Nam", "Mùa Thu");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID2`, `National`, `TranslateLanguage`, `seasons`) VALUES ("1", "book2","Sử kí toàn thư", 1024, "Lịch sử Việt Nam", 2012, 2, "Việt Nam", "Việt Nam", "Mùa Xuân");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID2`, `National`, `TranslateLanguage`, `seasons`) VALUES ("3", "book3","Harry Potter", 3297, "Truyện phép thuật", 2010, 1, "Việt Nam", "Anh", "Mùa Hạ");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID3`, `NameComics`, `SeriesName`, `Artist`) VALUES ("1", "book4","Cậu bé bút chì", 67, "Truyện cười", 2013, 1, "abc", "abc", "HaYuko");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID3`, `NameComics`, `SeriesName`, `Artist`) VALUES ("1", "book5","Doraemon", 53, "Truyện cười", 2009, 2, "abc", "abc", "DanTaTe");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID3`, `NameComics`, `SeriesName`, `Artist`) VALUES ("1", "book6","TotToChan", 234, "Truyện tuổi thơ", 1982, 3, "abc", "abc", "Chu Thán");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID4`, `NameBook`, `Months`, `Type`) VALUES ("2", "book7","Tuổi Hồng", 32, "Tạp chí trẻ", 2019, 1, "Sống tự do", "6", "Hàng tuần");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID4`, `NameBook`, `Months`, `Type`) VALUES ("3", "book8","Else", 65, "Tạp chí thời trang", 2021, 2, "Làm sao để phong cách", "2", "Hàng quý");
INSERT INTO book (`publisherID`, `ISBN`, `Title`, `Numberofpage`, `summary`, `year`, `ID4`, `NameBook`, `Months`, `Type`) VALUES ("3", "book9","Pháp luật", 123, "Tạp chí pháp luật", 2020, 3, "Nói không với tệ nạn", "1", "Hàng tháng");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (2, 1, 223000, 0, "16/01/2021");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (3, 22, 89000, 0, "12/12/2017");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (4, 67, 23000, 0, "22/08/2012");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (5, 12, 126000, 0, "12/12/2018");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (6, 51, 223000, 0, "22/09/2015");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (7, 61, 244500, 0, "01/11/2014");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (8, 54, 45000, 0, "22/06/2016");
INSERT INTO bookitem (`bookID`, `InStock`, `Price`, `Discount`, `Date`) VALUES (9, 4, 67100, 0, "17/05/2019");

INSERT INTO manufacturerclothes (`name`, `country`, `description`) VALUES ("Germe", "Hà Nội", "Thời trang giới trẻ");
INSERT INTO manufacturerclothes (`name`, `country`, `description`) VALUES ("Verache", "Pháp", "Thời trang cao cấp");
INSERT INTO manufacturerclothes (`name`, `country`, `description`) VALUES ("Gucci", "Ý", "Thời trang con ong");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID3`,`Type3`, `Length`,`PocketAvailable`) VALUES (1, "Phụ nữ", "Quần mèo cào", "Vải bò", 1, "Vải bò đen" , "75cm", "Yes");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID3`,`Type3`, `Length`,`PocketAvailable`) VALUES (2, "Trẻ em", "Quần vải", "Vải bông", 2, "Vải bông cao cấp" , "40cm", "No");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID3`,`Type3`, `Length`,`PocketAvailable`) VALUES (3, "Đàn ông", "Quần đùi", "Vải cotton", 3, "Vải cotton Trung Quốc" , "90cm", "Yes");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID2`,`Type2`, `FashionList`,`SleeveType`) VALUES (2, "Phụ nữ", "Váy hoa", "Vải voan", 1, "Váy hoa mỏng" , "abc", "Dài");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID2`,`Type2`, `FashionList`,`SleeveType`) VALUES (1, "Phụ nữ", "Váy trễ vai", "Vải cotton", 2, "Váy trễ vai ngang tay" , "abc", "Lửng");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID2`,`Type2`, `FashionList`,`SleeveType`) VALUES (3, "Phụ nữ", "Váy chữ V", "Vải co dãn", 3, "Váy body chữ V" , "abc", "Không có tay");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID4`,`Type4`, `Length2`, `Age`,`FashionList2`) VALUES (3, "Đàn ông", "Quần đùi mỏng", "Vải co dãn", 1, "Vải chão" , "40cm", "Người trung niên" , "cdf");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID4`,`Type4`, `Length2`, `Age`,`FashionList2`) VALUES (2, "Phụ nữ", "Quần đùi mỏng", "Vải voan", 2, "Vải voan không thấm nước" , "50cm", "Thanh thiếu niên" , "cdf");
INSERT INTO clothes (`ManufacturerClothesID`, `Gender`, `Type`, `Material`, `ID4`,`Type4`, `Length2`, `Age`,`FashionList2`) VALUES (2, "Trẻ em", "Quần đùi ngắn", "Vải cotton", 3, "Vải cotton nhập khẩu" , "20cm", "Trẻ dưới 5 tuổi" , "cdf");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (1, 31, 834000, 0, "16/01/2021");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (2, 12, 134000, 0, "16/01/2021");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (3, 25, 674000, 0, "12/12/2017");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (4, 37, 324000, 0, "22/08/2012");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (5, 42, 564000, 0, "12/12/2018");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (6, 56, 223000, 0, "22/09/2015");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (7, 51, 244500, 0, "01/11/2014");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (8, 5, 755000, 0, "22/06/2016");
INSERT INTO clothesitem (`ClothesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (9, 4, 277100, 0, "17/05/2019");
INSERT INTO `manufacturershoes` VALUES (1,'Adidas','Mỹ','Giày đẹp'),(2,'Bitis','Việt Nam','Nâng niu bàn chân Việt'),(3,'Juno','Việt Nam','Thoải mái chạy nhảy');
INSERT INTO `shoes` VALUES (1,1,'Trẻ em','23kg','Thu 1992','Vải cứng',1,'Cổ điển','Giày cổ ngắn','Queen_King',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(2,2,'Thanh niên','Từ 40-80kg','Xuân 2018','Vải da lộn',2,'Hiện đại','Giày cổ thấp','Hunter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(3,3,'Người lớn tuổi','40-60kg','Hạ 2011','Da Cá Sấu',3,'Thời trang','Giày cao cổ','Break the rule',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(4,2,'Thanh niên','Từ 30-80kg','Thu 2014','Da',NULL,NULL,NULL,NULL,1,'60cm','Boot cao','Your fashion','Thời trang','abc',NULL,NULL,NULL,NULL),(5,1,'Thanh niên','Từ 30-80kg','Hạ 2019','Jean',NULL,NULL,NULL,NULL,2,'40cm','Boot lửng','Classic','Cổ điển','abc',NULL,NULL,NULL,NULL),(6,1,'Thanh niên','Từ 30-80kg','Thu 2020','Vải da lộn',NULL,NULL,NULL,NULL,3,'20cm','Boot cổ thấp','Cá tính','Hiện đại','abc',NULL,NULL,NULL,NULL),(7,2,'Đàn ông','Từ 50-80kg','Hạ 2012','Cói',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'Thời trang','Dép tông Lào','Thoải mái là chính bạn'),(8,2,'Phụ nữ','Từ 40-50kg','Xuân 2020','Vải',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'Hiện đại','Dép chiến binh','Star'),(9,2,'Trẻ em','Dưới 23kg','Hạ 2017','Nhựa dẻo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,'Hiện đại','Dép tổ ong','Your');
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (1, 41, 432000, 0, "06/01/2011");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (2, 24, 144000, 0, "16/11/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (3, 25, 764000, 0, "12/02/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (4, 3, 234000, 0, "25/08/2013");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (5, 4, 434000, 0, "17/12/2021");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (6, 64, 784000, 0, "28/09/2015");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (7, 23, 257500, 0, "13/11/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (8, 35, 455000, 0, "21/06/2016");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (9, 1, 894600, 0, "07/05/2019");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (2, 24, 144000, 0, "16/11/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (3, 25, 764000, 0, "12/02/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (4, 3, 234000, 0, "25/08/2013");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (5, 4, 434000, 0, "17/12/2021");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (6, 64, 784000, 0, "28/09/2015");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (7, 23, 257500, 0, "13/11/2014");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (8, 35, 455000, 0, "21/06/2016");
INSERT INTO shoesitem (`ShoesID`, `Quantity`, `Price`, `Discount`, `Date`) VALUES (9, 1, 894600, 0, "07/05/2019");

INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('Samsung', 'HQ', 'Samsung');
INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('vin', 'VN', 'vin');
INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('lg', 'HQ', 'lg');
INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('apple', 'My', 'apple');
INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('dell', 'My', 'dell');
INSERT INTO manufacturerelectronics (`name`, `country`, `description`) VALUES ('asus', 'My', 'asus');
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`, `id2`, `storage`, `ram`, `operationsystem`, `screenwidth`, `resolution`, `touchable`) VALUES (1, 'Galaxy S6', '2016', 'IP67', 'True', 1, '256gb', '4gb', 'android 6.2', '5.2', '1920x1080', 1);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`, `id2`, `storage`, `ram`, `operationsystem`, `screenwidth`, `resolution`, `touchable`) VALUES (4, 'IPhone X', '2016', 'IP67', 'True', 2, '512gb', '4gb', 'IOS 11', '5.8', '1920x1080', 1);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`, `id2`, `storage`, `ram`, `operationsystem`, `screenwidth`, `resolution`, `touchable`) VALUES (3, 'LG ThinQ V6', '2019','IP67', 'True', 3, '512gb', '6gb', 'android 8', '5.8', '1920x1080', 1);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id3`, `screenwidth2`, `resolution2`, `disk`, `ram2`, `operationsystem2`, `touchable2`) VALUES (2, 'VietLap', '2020', 'Army', 'True', 1 , '15.3', '1920x1080', '512gb', '8gb', 'windows10', 0);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id3`, `screenwidth2`, `resolution2`, `disk`, `ram2`, `operationsystem2`, `touchable2`) VALUES (5, 'Dell XPS 1156', '2019', 'Army', 'True', 2 , '15.3', '1920x1080', '1tb', '8gb', 'windows10', 0);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id3`, `screenwidth2`, `resolution2`, `disk`, `ram2`, `operationsystem2`, `touchable2`) VALUES (6, 'Asus Zen 2020', '2020', 'Army', 'True', 3 , '17.2', '1920x1080', '1tb', '16gb', 'windows11', 0);
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id4`, `disk2`, `ram3`, `operationsystem3`) VALUES (4, 'Mac 2020', '2020', 'Army', 'False', 1 , '1tb', '32gb', 'MacOS 11');
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id4`, `disk2`, `ram3`, `operationsystem3`) VALUES (5, 'Dell Power x6', '2021', 'Army', 'False', 2 , '1tb', '16gb', 'windows10');
INSERT INTO electronic (`manufacturerelectronicsID`, `name`, `year`, `certificates`, `safetyclaims`,  `id4`, `disk2`, `ram3`, `operationsystem3`) VALUES (6, 'Asus Case 2020', '2020', 'Army', 'False', 3 , '1tb', '16gb', 'windows10');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (1, 100, 2000.0, 0, '9-10-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (2, 25, 1500.0, 0, '23-10-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (3, 55, 900.0, 0, '6-10-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (4, 35, 3000.0, 0, '11-11-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (5, 8, 3500.0, 0, '4-9-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (6, 12, 2900.0, 0, '5-9-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (7, 33, 5000.0, 0, '24-10-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (8, 67, 4500.0, 0, '16-10-2021');
INSERT INTO electronicitem (`electronicid`, `quantity`, `price`, `discount`, `date`) VALUES (9, 4, 3700.0, 0, '6-11-2021');